export const CHANGE_GLOBAL = 'CHANGE_GLOBAL';
export const CHANGE_BUDGETNAME = 'CHANGE_BUDGETNAME';
export const CHANGE_AUTHORITY = 'CHANGE_AUTHORITY';
export const CHANGE_REGIN = 'CHANGE_REGIN';
export const CHANGE_PROJECT = 'CHANGE_PROJECT';



